# Settings for the app
app:
  # HTML Title
  title: Put Your Money Where Your Map Is
  # Header name
  name: Put Your Money Where Your Map Is
  # Meta description that will show up in Google search results
  meta_description:  "Capital budget requests for the Brooklyn CB6 district"
  
  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 40.68304631549296
      lng: -73.97699687957764
    zoom: 14
    minZoom: 14
    maxZoom: 19
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-uhk6289l/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  building-approved:
    label: _(Approved Building/Facility)
    rules:
      - condition: '"{{location_type}}" === "building-approved"'
        # Display landmarks as icons
        icon:
          iconUrl: /static/css/images/building-gold.png
          shadowUrl: /static/css/images/shadow-square-gold.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
        focus_icon:
          iconUrl: /static/css/images/building-gold.png
          shadowUrl: /static/css/images/shadow-square-white.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
  street-approved:
    label: _(Approved Roadway/Streetscape)
    rules:
      - condition: '"{{location_type}}" === "street-approved"'
        icon:
          iconUrl: /static/css/images/cone-gold.png
          shadowUrl: /static/css/images/shadow-square-gold.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
        focus_icon:
          iconUrl: /static/css/images/cone-gold.png
          shadowUrl: /static/css/images/shadow-square-white.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
  park-approved:
    label: _(Approved Park/Open Space)
    rules:
      - condition: '"{{location_type}}" === "park-approved"'
        icon:
          iconUrl: /static/css/images/tree-gold.png
          shadowUrl: /static/css/images/shadow-round-gold.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
        focus_icon:
          iconUrl: /static/css/images/tree-gold.png
          shadowUrl: /static/css/images/shadow-round-white.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
  building-pending:
    label: _(Under Consideration Building/Facility)
    rules:
      - condition: '"{{location_type}}" === "building-pending"'
        # Display landmarks as icons
        icon:
          iconUrl: /static/css/images/building-gold.png
          shadowUrl: /static/css/images/shadow-square-gold.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
        focus_icon:
          iconUrl: /static/css/images/building-gold.png
          shadowUrl: /static/css/images/shadow-square-white.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
  street-pending:
    label: _(Under Consideration Roadway/Streetscape)
    rules:
      - condition: '"{{location_type}}" === "street-pending"'
        icon:
          iconUrl: /static/css/images/cone-gold.png
          shadowUrl: /static/css/images/shadow-square-gold.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
        focus_icon:
          iconUrl: /static/css/images/cone-gold.png
          shadowUrl: /static/css/images/shadow-square-white.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
  park-pending:
    label: _(Under Consideration Park/Open Space)
    rules:
      - condition: '"{{location_type}}" === "park-pending"'
        icon:
          iconUrl: /static/css/images/tree-gold.png
          shadowUrl: /static/css/images/shadow-round-gold.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
        focus_icon:
          iconUrl: /static/css/images/tree-gold.png
          shadowUrl: /static/css/images/shadow-round-white.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
  building:
    label: _(Building/Facility Need)
    rules:
      - condition: '"{{location_type}}" === "building"'
        # Display landmarks as icons
        icon:
          iconUrl: /static/css/images/building.png
          shadowUrl: /static/css/images/shadow-square.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
        focus_icon:
          iconUrl: /static/css/images/building.png
          shadowUrl: /static/css/images/shadow-square-white.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
  street:
    label: _(Roadway/Streetscape Need)
    rules:
      - condition: '"{{location_type}}" === "street"'
        icon:
          iconUrl: /static/css/images/cone.png
          shadowUrl: /static/css/images/shadow-square.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
        focus_icon:
          iconUrl: /static/css/images/cone.png
          shadowUrl: /static/css/images/shadow-square-white.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
  park:
    label: _(Park/Open Space Need)
    rules:
      - condition: '"{{location_type}}" === "park"'
        icon:
          iconUrl: /static/css/images/tree.png
          shadowUrl: /static/css/images/shadow-round.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
        focus_icon:
          iconUrl: /static/css/images/tree.png
          shadowUrl: /static/css/images/shadow-round-white.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
  building-rejected:
    label: _(Rejected Building/Facility)
    rules:
      - condition: '"{{location_type}}" === "building-rejected"'
        # Display landmarks as icons
        icon:
          iconUrl: /static/css/images/building-gray.png
          shadowUrl: /static/css/images/shadow-square.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
        focus_icon:
          iconUrl: /static/css/images/building-gray.png
          shadowUrl: /static/css/images/shadow-square-white.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
  street-rejected:
    label: _(Rejected Roadway/Streetscape)
    rules:
      - condition: '"{{location_type}}" === "street-rejected"'
        icon:
          iconUrl: /static/css/images/cone-gray.png
          shadowUrl: /static/css/images/shadow-square.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
        focus_icon:
          iconUrl: /static/css/images/cone-gray.png
          shadowUrl: /static/css/images/shadow-square-white.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
  park-rejected:
    label: _(Rejected Park/Open Space)
    rules:
      - condition: '"{{location_type}}" === "park-rejected"'
        icon:
          iconUrl: /static/css/images/tree-gray.png
          shadowUrl: /static/css/images/shadow-round.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
        focus_icon:
          iconUrl: /static/css/images/tree-gray.png
          shadowUrl: /static/css/images/shadow-round-white.png
          iconSize: [31, 32]
          shadowSize: [31, 32]
          iconAnchor: [16, 25]
activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Identify a need)
  show_list_button_label: _(List All Places)
  show_map_button_label: _(Show the Map)
  title: _(Provide more information)
  action_text: _(identified)
  anonymous_name: _(Someone)
  submit_button_label: _(Add to map)
  items:
    - prompt: Type of need
      type: select
      options:
        - label: _(Building/Facility Need)
          value: building
        - label: _(Roadway/Streetscape Need)
          value: street
        - label: _(Park/Open Space Need)
          value: park
      name: location_type
    - prompt: _(District wide?)
      type: checkbox
      name: district-wide
      attrs:
        - key: value
          value: _(District Wide)
        - key: label
          value: _(District wide project)
    - prompt: _(Short description of the need)
      type: text
      name: project_title
      optional: false
      attrs:
        - key: size
          value: 30
        - key: placeholder
          value: _(What and where?)
        - key: required
    - prompt: _(Explain more about the need)
      type: textarea
      name: description
      optional: false
      attrs:
        - key: placeholder
          value: Explain the need.
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: false
      attrs:
        - key: size
          value: 30
        - key: required
    - prompt: _(Your Email (will not be shown on the map))
      type: text
      optional: false
      name: private-email
      attrs:
        - key: size
          value: 30
        - key: required
survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: Welcome
    slug: welcome
    name: welcome
    start_page: true
  - title: How To Use
    slug: how-to
    name: overview
  - title: Frequently Asked Questions
    slug: faq
    name: faq

notifications:
  on_new_place: true
  submitter_email_field: "private-email"